config/routes.rb
Rails.application.routes.draw do
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :current_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all
  end

  def show

  end

  def new
    @dog = Dog.new
  end

  def create
    dog = Dog.create(dog_params)

    redirect_to dog_path(dog)
  end

  def edit

  end

  def update
    @dog.update(dog_params)
    redirect_to dog_path(@dog)
  end

  def destroy
    @dog.destroy

    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :motto)
  end

  def current_dog
    @dog = Dog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<h3>Update Dog Details</h3>
<%= simple_form_for(@dog, wrapper: :horizontal_form) do |f| %>
  <%= f.input :name, placeholder: 'Name',  required: true%>
  <%= f.input :motto, placeholder: 'Motto', required: true %>
  <%= f.button :submit %>
<% end %>

<td><%= link_to 'Back', dogs_path %></td>

app/views/dogs/index.html.erb
<ul>
  <% @dogs.each do |dog| %>
    <li><%= link_to dog.name, dog_path(dog)  %></li>
  <% end %>
</ul>
<table>
  <% @dogs.each do |dog| %>
    <tr>
      <td><%= link_to dog.name, dog_path(dog) %></td>
      <td><%= button_to 'Edit', edit_dog_path(dog), method: 'get'%></td>
      <td><%= button_to 'Remove', dog_path(dog), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Dog", new_dog_path %>

app/views/dogs/new.html.erb
<h3>Create a Dog</h3>

<%= simple_form_for(@dog, wrapper: :horizontal_form) do |f| %>
  <%= f.input :name, placeholder: 'Name',  required: true%>
  <%= f.input :motto, placeholder: 'Motto', required: true %>
  <%= f.button :submit %>
<% end %>

<td><%= link_to 'Back', dogs_path %></td>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<h4>"<%= @dog.motto %>"</h4>

<%= link_to 'Remove', @dog, method: :delete, data: { confirm: 'Are you sure?' } %>

<td><%= link_to 'Back', dogs_path %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>